def escape(frames: list[memoryview], full: bool = True) -> bytearray: ...

class PppDecoder:
    def __init__(self) -> None: ...
    def unescape(self, data: bytes) -> list[memoryview | bytearray]: ...
