def sstp_to_ppp(frames: list[memoryview], full: bool = True) -> bytearray: ...

class PppDecoder:
    def __init__(self) -> None: ...
    def ppp_to_sstp(self, data: bytes, ctrl_only: bool) -> bytearray: ...
